name: "Compile markdown to stylized HTML"

on:
        workflow_dispatch:
        push:
                branches:
                        - main


jobs:
        compile:
                runs-on: 'ubuntu-latest'
                steps:
                        - uses: actions/checkout@v2
                        - name: Merge main to github pages
                          uses: devmasx/merge-branch@v1.3.1
                          with:
                            type: now
                            target_branch: github_pages
                            github_token: ${{ github.token }}