name: "Compile markdown to stylized HTML"

on:
        workflow_dispatch:
        push:
                branches:
                        - main


jobs:
        compile:
                runs-on: 'ubuntu-latest'
                steps:
                        - uses: actions/checkout@v2

                        - name: Install node's assets
                          uses: actions/setup-node@v2
                          with:
                                  node-version: '12'
                                  
                        - name: "NPM install"
                          run: "npm install"
                        
                        - name: "NPM compile asset"
                          run: "npm run compile"

                        - name: Merge main to github_pages
                          uses: devmasx/merge-branch@v1.3.1
                          with:
                                  type: now
                                  from_branch: main
                                  github_token: ${{ github.token }}

                        - name: Commit build # commit if differences are tracked after updates (previous step)
                          uses: stefanzweifel/git-auto-commit-action@v4
                          with:
                              commit_message: HTML build
                              commit_user_name: GitHub Actions Bot
                              commit_author: GitHub Action <actions@github.com>
                              skip_dirty_check: false
                              push_options:  --force