name: "Compile markdown to stylized HTML"

on:
        workflow_dispatch:
        push:
                branches:
                        - main


jobs:
        compile:
                runs-on: 'ubuntu-latest'
                steps:
                        - name: checkout to main
                          uses: actions/checkout@v2
                          with:
                                  ref: ${{ github.read_ref }}

                        - name: Install node's assets
                          uses: actions/setup-node@v2
                          with:
                                  node-version: '12'

                        - run: npm install
                        - run: npm run compile
                        
                        - name: checkout to github_pages for commit
                          uses: actions/checkout@v2
                          with:
                                  ref: ${{ github.read_ref }}
  
                        - name: Commit build # commit if differences are tracked after updates (previous step)
                          uses: stefanzweifel/git-auto-commit-action@v4
                          with:
                              commit_message: HTML build
                              commit_user_name: GitHub Actions Bot
                              commit_author: GitHub Action <actions@github.com>
                              skip_dirty_check: false
                              push_options:  --force
